.MODEL TINY
.8086
.DATA
	PORT_FAN EQU 00H
	PORT_B EQU 02H
	PORT_KEYPAD EQU 04H
	PORT_CREG1 EQU 06H
	PORT_TIMER EQU 08H
	PORT_CREG2 EQU 0EH
	PORT_TIME EQU 10H
	PORT_CREG3 EQU 16H
	SPEED0 EQU 00H
	SPEED1 EQU 3FH
	SPEED2 EQU 5FH
	SPEED3 EQU 7FH
	SPEED4 EQU 9FH
	SPEED5 EQU 0BFH
	DAT DB 'A' , 'B' , 'C' , 'D' , 'E' , 'F' , 'G' , 'H' , 'I' , 'J'
.CODE 
.STARTUP

	MOV AL , 81H
	OUT PORT_CREG1 , AL

	MOV AL , SPEED0
	OUT PORT_FAN , AL
	
	MOV AL , 0FDH
	OUT PORT_B , AL

	MOV AL , 0FFH
	OUT PORT_B , AL

	MOV AL , 30H
	OUT PORT_CREG2 , AL
	
	MOV AL , 9BH
	OUT PORT_CREG3 , AL
	
	MOV BL , 00H
	MOV DL , 00H

L0:	
X1:	MOV AL , 00H
	OUT PORT_KEYPAD , AL
	IN AL , PORT_KEYPAD
	AND AL , 0FH
	CMP AL , 0FH
	JNZ X1
X2:	MOV AL , 00H
	OUT PORT_KEYPAD , AL
	IN AL , PORT_KEYPAD
	AND AL , 0FH
	CMP AL , 0FH
	JZ X2
	MOV CX , 1100	
	A9: LOOP A9
	MOV AL , 00H
	OUT PORT_KEYPAD , AL
	IN AL , PORT_KEYPAD
	AND AL , 0FH
	CMP AL , 0FH
	JZ X2
	MOV SI , OFFSET DAT
	CMP AL , 0DH
	JNZ X3
	ADD SI , 4
	JMP X5
X3: 	CMP AL , 0EH
	JNZ X5
	ADD SI , 8
X5:	MOV AL , 7FH
	OUT PORT_KEYPAD , AL
	IN AL , PORT_KEYPAD
	AND AL , 0FH
	CMP AL , 0FH
	JZ X6
	MOV AL , [SI]
	JMP L1
X6: 	MOV AL , 0BFH
	OUT PORT_KEYPAD , AL
	IN AL , PORT_KEYPAD
	AND AL , 0FH
	CMP AL , 0FH
	JZ X7
	MOV AL , [SI+1]
	JMP L1
X7:	MOV AL , 0DFH
	OUT PORT_KEYPAD , AL
	IN AL , PORT_KEYPAD
	AND AL , 0FH
	CMP AL , 0FH
	JZ X8
	MOV AL , [SI+2]
	JMP L1	
X8: 	MOV AL , [SI+3]

L1:	CMP AL , 'A'
	JNZ L2
	CMP DL , 0
	JNZ L0
	MOV BL , SPEED1
	MOV AL , BL
	OUT PORT_FAN , AL
	MOV DL , 1
	MOV AL , 0FDH
	OUT PORT_B , AL
	MOV CX , 1100
	A8: LOOP A8
	MOV AL , 00H
	MOV AL , 0FFH 
	OUT PORT_B , AL
	JMP L0

L2: 	CMP AL , 'B'
	JNZ L3
	CMP DL , 0
	JZ L0
	MOV BL , SPEED0
	MOV AL , BL
	OUT PORT_FAN , AL
	MOV DL , 0
	MOV AL , 0FDH
	OUT PORT_B , AL
	MOV CX , 1100
	A7: LOOP A7
	MOV AL , 00H
	MOV AL , 0FFH 
	OUT PORT_B , AL
	JMP L0
	
L3:	CMP AL , 'C'
	JNZ L4
	CMP DL , 0
	JZ L0
	CMP BL , SPEED5
	JZ L0
	ADD BL , 20H
	MOV AL , BL
	OUT PORT_FAN , AL	
	JMP L0

L4:	CMP AL , 'D'
	JNZ L5
	CMP DL , 0
	JZ L0
	CMP BL , SPEED1
	JZ L0
	SUB BL , 20H
	MOV AL , BL
	OUT PORT_FAN , AL
	JMP L0

L5:	CMP AL , 'E'
	JNZ L6
	CMP DL , 0
	JZ L0
	MOV BL , SPEED1
	MOV AL , BL
	OUT PORT_FAN , AL
	JMP L0

L6:	CMP AL , 'F'
	JNZ L7
	CMP DL , 0
	JZ L0
	MOV BL , SPEED2
	MOV AL , BL
	OUT PORT_FAN , AL
	JMP L0

L7:	CMP AL , 'G'
	JNZ L8
	CMP DL , 0
	JZ L0
	MOV BL , SPEED3
	MOV AL , BL
	OUT PORT_FAN , AL
	JMP L0

L8:	CMP AL , 'H'
	JNZ L9
	CMP DL , 0
	JZ L0
	MOV BL , SPEED4
	MOV AL , BL
	OUT PORT_FAN , AL
	JMP L0

L9:	CMP AL , 'I'
	JNZ L10
	CMP DL , 0
	JZ L0
	MOV BL , SPEED5
	MOV AL , BL
	OUT PORT_FAN , AL
	JMP L0

L10:	CMP DL , 00H
	JZ L0
	IN AL , PORT_TIME
	AND AL , 60H
	CMP AL , 00H
	JNZ L11
	MOV AX , 0001H
	OUT PORT_TIMER , AL
	MOV AL , AH
	OUT PORT_TIMER , AL
	MOV AL , 0FEH
	OUT PORT_B , AL
	MOV CX , 1100
	A6: LOOP A6
	MOV AL , 00H
	MOV AL , 0FFH
	OUT PORT_B , AL
	JMP L0
L11: 	CMP AL , 20H
	JNZ L12
	MOV AX , 3600
	OUT PORT_TIMER , AL
	MOV AL , AH
	OUT PORT_TIMER , AL
	MOV AL , 0FEH
	OUT PORT_B , AL
	MOV CX , 1100
	A5: LOOP A5
	MOV AL , 00H
	MOV AL , 0FFH
	OUT PORT_B , AL
	JMP L0
L12: 	CMP AL , 40H
	JNZ L13
	MOV AX , 7200
	OUT PORT_TIMER , AL
	MOV AL , AH
	OUT PORT_TIMER , AL
	MOV AL , 0FEH
	OUT PORT_B , AL
	MOV CX , 1100
	A4: LOOP A4
	MOV AL , 00H
	MOV AL , 0FFH
	OUT PORT_B , AL
	JMP L0
L13:	MOV AX , 10800
	OUT PORT_TIMER , AL
	MOV AL , AH
	OUT PORT_TIMER , AL
	MOV AL , 0FEH
	OUT PORT_B , AL
	MOV CX , 1100
	A3: LOOP A3
	MOV AL , 00H
	MOV AL , 0FFH
	OUT PORT_B , AL
	JMP L0

	
.EXIT
END	